CREATE TABLE `video_jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`original_video_url` text NOT NULL,
	`original_video_key` text NOT NULL,
	`original_filename` varchar(255) NOT NULL,
	`file_size` int NOT NULL,
	`duration` int,
	`user_requirement` text NOT NULL,
	`asr_method` enum('whisper','aliyun') NOT NULL DEFAULT 'whisper',
	`status` enum('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
	`progress` int NOT NULL DEFAULT 0,
	`current_step` varchar(100),
	`error_message` text,
	`transcript_url` text,
	`transcript_key` text,
	`final_video_url` text,
	`final_video_key` text,
	`subtitle_url` text,
	`subtitle_key` text,
	`selected_segments` json,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`completed_at` timestamp,
	CONSTRAINT `video_jobs_id` PRIMARY KEY(`id`)
);
